# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: galorenz <galorenz@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/11/26 18:03:57 by galorenz          #+#    #+#              #
#    Updated: 2025/11/26 21:40:36 by galorenz         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #



rifai e' sbagliato
NAME=

CC =
CFLAGS =
SRC =

all:$(NAME)
$(NAME) :
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)

fclean:
	rm -f $(NAME)

re:fclean all

.PHONY: all fclean re